name: Cogniflex

services:
  db:
    image: postgres:18
    container_name: cogniflex-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend-network
    restart: unless-stopped

  redis:
    image: redis:8
    container_name: cogniflex-redis
    volumes:
      - redis_data:/data
    networks:
      - backend-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: cogniflex-backend:latest
    container_name: cogniflex-backend
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - REDIS_HOST=redis
      - ML_SERVICE_HOST=ml-service
    volumes:
      - ./backend/src/main/resources:/app/config:ro
    depends_on:
      - db
      - redis
      - ml-service
    networks:
      - backend-network
      - analysis-network
    restart: unless-stopped

  ml-service:
    build:
      context: .
      dockerfile: ml-service/Dockerfile
    image: cogniflex-ml-service:latest
    container_name: cogniflex-ml-service
    ports:
      - "50051:50051"
    env_file:
      - .env
    volumes:
      - ./ml-service/config.yaml:/app/ml-service/config.yaml:ro
      - ./ml-service/weights:/app/ml-service/weights:ro
    networks:
      - analysis-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge
  analysis-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: