package io.github.duckysmacky.cogniflex_backend.Services;

import io.github.duckysmacky.cogniflex_backend.Dtos.AnalyzeResultResponse;
import io.github.duckysmacky.cogniflex_backend.Dtos.CreateTextDetectionRequest;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;

@Service
public class DetectionService {

    public AnalyzeResultResponse analyzeText(CreateTextDetectionRequest request) {
        String normalizedText = request.text().trim().toLowerCase();

        if (normalizedText.contains("chatgpt") || normalizedText.contains("generated by ai")) {
            return new AnalyzeResultResponse(1, 0.89);
        }

        return new AnalyzeResultResponse(0, 0.62);
    }

    public AnalyzeResultResponse analyzeMedia(MultipartFile file) {
        if (file.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "File is empty");
        }

        String contentType = file.getContentType();

        if (contentType == null) {
            return new AnalyzeResultResponse(1, 0.50);
        }

        if (contentType.startsWith("image/")) {
            return new AnalyzeResultResponse(1, 0.67);
        }

        if (contentType.startsWith("video/")) {
            return new AnalyzeResultResponse(1, 0.63);
        }

        return new AnalyzeResultResponse(1, 0.55);
    }
}
