package io.github.duckysmacky.cogniflex.services;

import io.github.duckysmacky.cogniflex.dto.AnalyzeResultResponse;
import io.github.duckysmacky.cogniflex.dto.CreateHistoryItemRequest;
import io.github.duckysmacky.cogniflex.enums.DetectionKind;
import io.github.duckysmacky.cogniflex.enums.InputType;
import io.github.duckysmacky.cogniflex.enums.MediaType;
import org.springframework.stereotype.Service;

@Service
public class DetectionService {

    private final HistoryService historyService;

    public DetectionService(HistoryService historyService) {
        this.historyService = historyService;
    }

    public AnalyzeResultResponse analyzeText(String text) {
        String normalizedText = text.trim().toLowerCase();

        AnalyzeResultResponse response;
        if (normalizedText.contains("chatgpt") || normalizedText.contains("generated by ai")) {
            response = new AnalyzeResultResponse(DetectionKind.AI_GENERATED, 0.89);
        } else {
            response = new AnalyzeResultResponse(DetectionKind.HUMAN, 0.62);
        }

        historyService.createHistoryItem(new CreateHistoryItemRequest(
                InputType.TEXT,
                null,
                response.kind(),
                response.accuracy()
        ));

        return response;
    }

    public AnalyzeResultResponse analyzeMedia(MediaType mediaType) {
        AnalyzeResultResponse response =
                mediaType == MediaType.IMAGE
                        ? new AnalyzeResultResponse(DetectionKind.AI_GENERATED, 0.67)
                        : new AnalyzeResultResponse(DetectionKind.AI_GENERATED, 0.63);

        historyService.createHistoryItem(new CreateHistoryItemRequest(
                InputType.MEDIA,
                mediaType,
                response.kind(),
                response.accuracy()
        ));

        return response;
    }
}
