package io.github.duckysmacky.cogniflex.clients;

import io.github.duckysmacky.cogniflex.dto.AnalyzeResultResponse;
import io.github.duckysmacky.cogniflex.enums.DetectionKind;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

@Service
@Profile("stub-ml")
public class StubMlClient implements MLClient {

    @Override
    public AnalyzeResultResponse analyzeText(String normalizedText) {
        String loweredText = normalizedText.toLowerCase();

        if (loweredText.contains("chatgpt") || loweredText.contains("generated by ai")) {
            return new AnalyzeResultResponse(DetectionKind.AI_GENERATED, 0.89);
        }

        return new AnalyzeResultResponse(DetectionKind.HUMAN, 0.62);
    }

    @Override
    public AnalyzeResultResponse analyzeImage(byte[] imageContent) {
        return new AnalyzeResultResponse(DetectionKind.AI_GENERATED, 0.67);
    }

    @Override
    public AnalyzeResultResponse analyzeVideo(byte[] videoContent) {
        return new AnalyzeResultResponse(DetectionKind.AI_GENERATED, 0.63);
    }
}
