spring:
  jpa:
    show-sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  cors:
    allowed-origins-patterns: "*"
    allowed-methods: [GET, POST, OPTIONS]
    allowed-headers: ["Content-Type", "Authorization"]
    allow-credentials: true