spring:
  jpa:
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        security: debug
        web:
          cors: TRACE
      
app:
  cors:
    allowed-origins-patterns: "*"
    allowed-methods: [GET, POST, DELETE, PUT, OPTIONS]
    allowed-headers: ["*"]
    allow-credentials: true
  rate-limit:
    active: false
    path-patterns: 
      - /app/analyze/**
    capacity: 100
    refill-greedy-capacity: 100
    refill-greedy-duration-seconds: 60

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true