spring:
  jpa:
    show-sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  cors:
    allowed-origins-patterns: "*"
    allowed-methods: [GET, POST, OPTIONS]
    allowed-headers: ["Content-Type", "Authorization"]
    allow-credentials: true
  rate-limit:
    active: false
    path-patterns: 
      - /app/analyze/**
    capacity: 100
    refill-greedy-capacity: 100
    refill-greedy-duration-seconds: 60